### ISSUE TITLE
Cloud-init

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [ashleyhood/php-lxd#29]
Hello,

I searched the documentation but found no reference to using Cloud-init:

```
  user.user-data: |
    #cloud-config
    package_upgrade: true
    packages:
      - package1
      - package2

```
